version: '3'
services:
  author:
    image: websites_aem_author
    container_name: websites_aem_author
    build:
      context: ./
      dockerfile: author/Dockerfile
    hostname: 'author'
    ports:
      - '4502:4502'
      - '5005:5005'
    volumes:
      - ./logs/author:/opt/aem/crx-quickstart/logs
    depends_on:
      - 'publisher'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
  publisher:
    image: websites_aem_publisher
    container_name: websites_aem_publisher
    build:
      context: ./
      dockerfile: publisher/Dockerfile
    hostname: 'publisher'
    ports:
      - '4503:4503'
      - '5006:5006'
    volumes:
      - ./logs/publisher:/opt/aem/crx-quickstart/logs
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 3G
  dispatcher:
    image: websites_aem_dispatcher
    container_name: websites_aem_dispatcher
    build:
      context: ./dispatcher
    hostname: 'dispatcher'
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - ./logs/dispatcher:/usr/local/apache2/logs
    environment:
      - DOMAIN=aem.local
    depends_on:
      - 'publisher'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 3G
